version: '3'
services:
  pc-apps:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PC_VERSION: "${PC_VERSION}"
        NODE_ENV: "${NODE_ENV}"
    container_name: pc_apps_dev
    ports:
      - "${PORT}:3000"
    environment:
      NODE_ENV: "${NODE_ENV}"
      PC_URL: "${PC_URL}"
      FACTOID_URL: "${FACTOID_URL}"