version: "3.8"
services:
  watch:
    image: containrrr/watchtower:${WATCHTOWER_IMAGE_TAG:-latest}
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE:-development}
    restart: always
    depends_on:
      - webapp
    container_name: watch
    environment:
      TZ: "America/Toronto"
      WATCHTOWER_SCHEDULE:
      WATCHTOWER_CLEANUP:
      WATCHTOWER_SCOPE:
    networks:
      -  app-ui-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["webapp"]
  webapp:
    image: pathwaycommons/app-ui:${APPUI_IMAGE_TAG:-latest}
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE:-development}
    restart: unless-stopped
    container_name: webapp
    ports:
      - "${APPUI_PORT:-3000}:3000"
    environment:
      PC_URL:
      NODE_ENV:
      FACTOID_URL:
    networks:
      - app-ui-network
  syblars:
    image: pathwaycommons/syblars:${SYBLARS_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: syblars
    ports:
      - "${SYBLARS_PORT:-9090}:3000"
    networks:
      - app-ui-network

networks:
  app-ui-network:
    driver: bridge
