version: "3.8"
services:
  webapp:
    image: pathwaycommons/app-ui:${APPUI_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: webapp
    ports:
      - "${APPUI_PORT:-3000}:3000"
    environment:
      PC_URL:
      NODE_ENV:
      FACTOID_URL:
    networks:
      - app-ui-network

networks:
  app-ui-network:
    driver: bridge
