const chai = require('chai');
const expect = chai.expect;
const {enrichment} = require('../../../server/enrichment-map/enrichment');

describe('test enrichment', function() {
  it('it should return an object', function() {
    return (enrichment('ATM')).then(function(res) {
      const result = { 'GO:0000726':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '76',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.013',
        't type': 'BP',
        't group': '8',
        't name': 'non-recombinational repair',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0006302':
      { signf: '!',
        pvalue: '1.13e-02',
        T: '196',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.005',
        't type': 'BP',
        't group': '8',
        't name': 'double-strand break repair',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0000729':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '23',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.043',
        't type': 'BP',
        't group': '8',
        't name': 'DNA double-strand break processing',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0006303':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '69',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.014',
        't type': 'BP',
        't group': '8',
        't name': 'double-strand break repair via nonhomologous end joining',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0008334':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '24',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.042',
        't type': 'BP',
        't group': '13',
        't name': 'histone mRNA metabolic process',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0071044':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '11',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.091',
        't type': 'BP',
        't group': '13',
        't name': 'histone mRNA catabolic process',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0006975':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '8',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.125',
        't type': 'BP',
        't group': '1',
        't name': 'DNA damage induced protein phosphorylation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0022618':
      { signf: '!',
        pvalue: '1.13e-02',
        T: '195',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.005',
        't type': 'BP',
        't group': '12',
        't name': 'ribonucleoprotein complex assembly',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:1905323':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '6',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.167',
        't type': 'BP',
        't group': '12',
        't name': 'telomerase holoenzyme complex assembly',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0010212':
      { signf: '!',
        pvalue: '8.13e-03',
        T: '95',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.011',
        't type': 'BP',
        't group': '5',
        't name': 'response to ionizing radiation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0010165':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '15',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.067',
        't type': 'BP',
        't group': '5',
        't name': 'response to X-ray',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0010332':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '25',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.040',
        't type': 'BP',
        't group': '5',
        't name': 'response to gamma radiation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0071478':
      { signf: '!',
        pvalue: '9.36e-03',
        T: '132',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.008',
        't type': 'BP',
        't group': '5',
        't name': 'cellular response to radiation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0071479':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '47',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.021',
        't type': 'BP',
        't group': '5',
        't name': 'cellular response to ionizing radiation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0071481':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '5',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.200',
        't type': 'BP',
        't group': '5',
        't name': 'cellular response to X-ray',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0071480':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '16',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.062',
        't type': 'BP',
        't group': '5',
        't name': 'cellular response to gamma radiation',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0031570':
      { signf: '!',
        pvalue: '9.86e-03',
        T: '153',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'DNA integrity checkpoint',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0000077':
      { signf: '!',
        pvalue: '9.62e-03',
        T: '143',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'DNA damage checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0044783':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '71',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.014',
        't type': 'BP',
        't group': '11',
        't name': 'G1 DNA damage checkpoint',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0031572':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '33',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.030',
        't type': 'BP',
        't group': '11',
        't name': 'G2 DNA damage checkpoint',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0051783':
      { signf: '!',
        pvalue: '9.62e-03',
        T: '143',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of nuclear division',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0032845':
      { signf: '!',
        pvalue: '9.49e-03',
        T: '137',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of homeostatic process',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0051784':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '50',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.020',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of nuclear division',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0032846':
      { signf: '!',
        pvalue: '1.00e-02',
        T: '159',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of homeostatic process',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0051304':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '65',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'chromosome separation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0032200':
      { signf: '!',
        pvalue: '1.00e-02',
        T: '160',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '11',
        't name': 'telomere organization',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0051983':
      { signf: '!',
        pvalue: '7.61e-03',
        T: '84',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.012',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of chromosome segregation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0051985':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '36',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.028',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of chromosome segregation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1905818':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '47',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.021',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of chromosome separation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1905819':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '32',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.031',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of chromosome separation',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0031577':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '33',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.030',
        't type': 'BP',
        't group': '11',
        't name': 'spindle checkpoint',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0071173':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '28',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.036',
        't type': 'BP',
        't group': '11',
        't name': 'spindle assembly checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1902806':
      { signf: '!',
        pvalue: '9.80e-03',
        T: '150',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of cell cycle G1/S phase transition',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:2000045':
      { signf: '!',
        pvalue: '9.49e-03',
        T: '136',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of G1/S transition of mitotic cell cycle',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1902749':
      { signf: '!',
        pvalue: '1.08e-02',
        T: '181',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of cell cycle G2/M phase transition',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:1902750':
      { signf: '!',
        pvalue: '7.64e-03',
        T: '86',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.012',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of cell cycle G2/M phase transition',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0010389':
      { signf: '!',
        pvalue: '1.05e-02',
        T: '175',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of G2/M transition of mitotic cell cycle',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0010972':
      { signf: '!',
        pvalue: '7.61e-03',
        T: '84',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.012',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of G2/M transition of mitotic cell cycle',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:2001020':
      { signf: '!',
        pvalue: '9.74e-03',
        T: '148',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of response to DNA damage stimulus',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0071156':
      { signf: '!',
        pvalue: '8.45e-03',
        T: '108',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.009',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of cell cycle arrest',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0042770':
      { signf: '!',
        pvalue: '8.85e-03',
        T: '118',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.008',
        't type': 'BP',
        't group': '11',
        't name': 'signal transduction in response to DNA damage',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0030330':
      { signf: '!',
        pvalue: '8.43e-03',
        T: '105',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'BP',
        't group': '11',
        't name': 'DNA damage response, signal transduction by p53 class mediator',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:2001252':
      { signf: '!',
        pvalue: '9.36e-03',
        T: '132',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.008',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of chromosome organization',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:2001251':
      { signf: '!',
        pvalue: '8.43e-03',
        T: '106',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.009',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of chromosome organization',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0007093':
      { signf: '!',
        pvalue: '9.86e-03',
        T: '152',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic cell cycle checkpoint',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0044774':
      { signf: '!',
        pvalue: '8.43e-03',
        T: '104',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic DNA integrity checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0044773':
      { signf: '!',
        pvalue: '8.13e-03',
        T: '96',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic DNA damage checkpoint',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0044818':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '22',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.045',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic G2/M transition checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0007095':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '14',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.071',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic G2 DNA damage checkpoint',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0000070':
      { signf: '!',
        pvalue: '9.36e-03',
        T: '130',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.008',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic sister chromatid segregation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0051306':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '46',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.022',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic sister chromatid separation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:2001022':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '66',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of response to DNA damage stimulus',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0072395':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '68',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'signal transduction involved in cell cycle checkpoint',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0072401':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '67',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'signal transduction involved in DNA integrity checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0072422':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '67',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'signal transduction involved in DNA damage checkpoint',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0072413':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '65',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'signal transduction involved in mitotic cell cycle checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1902403':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '65',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'signal transduction involved in mitotic DNA integrity checkpoint',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:1902402':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '65',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'signal transduction involved in mitotic DNA damage checkpoint',
        't depth': '4',
        'Q&T list': 'ATM' },
     'GO:1901796':
      { signf: '!',
        pvalue: '1.01e-02',
        T: '164',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of signal transduction by p53 class mediator',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:1901798':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '19',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.053',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of signal transduction by p53 class mediator',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0043516':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '27',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.037',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of DNA damage response, signal transduction by p53 class mediator',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0043517':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '13',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.077',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of DNA damage response, signal transduction by p53 class mediator',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:1902807':
      { signf: '!',
        pvalue: '8.43e-03',
        T: '105',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of cell cycle G1/S phase transition',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:1902400':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '63',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.016',
        't type': 'BP',
        't group': '11',
        't name': 'intracellular signal transduction involved in G1 DNA damage checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0071158':
      { signf: '!',
        pvalue: '7.61e-03',
        T: '84',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.012',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of cell cycle arrest',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0033045':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '64',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.016',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of sister chromatid segregation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0044784':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '44',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.023',
        't type': 'BP',
        't group': '11',
        't name': 'metaphase/anaphase transition of cell cycle',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1902099':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '42',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.024',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of metaphase/anaphase transition of cell cycle',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1902100':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '30',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.033',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of metaphase/anaphase transition of cell cycle',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0033046':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '35',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.029',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of sister chromatid segregation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0007088':
      { signf: '!',
        pvalue: '9.43e-03',
        T: '134',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of mitotic nuclear division',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0033047':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '53',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.019',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of mitotic sister chromatid segregation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0010965':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '45',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.022',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of mitotic sister chromatid separation',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0007091':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '43',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.023',
        't type': 'BP',
        't group': '11',
        't name': 'metaphase/anaphase transition of mitotic cell cycle',
        't depth': '4',
        'Q&T list': 'ATM' },
     'GO:0030071':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '41',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.024',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of mitotic metaphase/anaphase transition',
        't depth': '4',
        'Q&T list': 'ATM' },
     'GO:0045839':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '42',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.024',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of mitotic nuclear division',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0033048':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '33',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.030',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of mitotic sister chromatid segregation',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:2000816':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '31',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.032',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of mitotic sister chromatid separation',
        't depth': '4',
        'Q&T list': 'ATM' },
     'GO:0000723':
      { signf: '!',
        pvalue: '9.74e-03',
        T: '147',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '11',
        't name': 'telomere maintenance',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0016233':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '54',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.019',
        't type': 'BP',
        't group': '11',
        't name': 'telomere capping',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0010833':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '77',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.013',
        't type': 'BP',
        't group': '11',
        't name': 'telomere maintenance via telomere lengthening',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0032204':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '75',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.013',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of telomere maintenance',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1904353':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '25',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.040',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of telomere capping',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:1904356':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '58',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.017',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of telomere maintenance via telomere lengthening',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0071897':
      { signf: '!',
        pvalue: '1.01e-02',
        T: '165',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '11',
        't name': 'DNA biosynthetic process',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0006278':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '67',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'RNA-dependent DNA biosynthetic process',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0007004':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '66',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '11',
        't name': 'telomere maintenance via telomerase',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0000731':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '72',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.014',
        't type': 'BP',
        't group': '11',
        't name': 'DNA synthesis involved in DNA repair',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:2000134':
      { signf: '!',
        pvalue: '8.33e-03',
        T: '101',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of G1/S transition of mitotic cell cycle',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0044819':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '70',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.014',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic G1/S transition checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0031571':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '70',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.014',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic G1 DNA damage checkpoint',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0072431':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '63',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.016',
        't type': 'BP',
        't group': '11',
        't name': 'signal transduction involved in mitotic G1 DNA damage checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0006977':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '62',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.016',
        't type': 'BP',
        't group': '11',
        't name': 'DNA damage response, signal transduction by p53 class mediator resulting in cell cycle arrest',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0051054':
      { signf: '!',
        pvalue: '1.02e-02',
        T: '168',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of DNA metabolic process',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0032206':
      { signf: '!',
        pvalue: '7.32e-03',
        T: '48',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.021',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of telomere maintenance',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1904358':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '34',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.029',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of telomere maintenance via telomere lengthening',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0051053':
      { signf: '!',
        pvalue: '8.44e-03',
        T: '107',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.009',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of DNA metabolic process',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0032205':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '35',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.029',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of telomere maintenance',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1904354':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '7',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.143',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of telomere capping',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:2000278':
      { signf: '!',
        pvalue: '7.74e-03',
        T: '88',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.011',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of DNA biosynthetic process',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0032210':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '51',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.020',
        't type': 'BP',
        't group': '11',
        't name': 'regulation of telomere maintenance via telomerase',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:2000573':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '58',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.017',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of DNA biosynthetic process',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0032212':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '32',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.031',
        't type': 'BP',
        't group': '11',
        't name': 'positive regulation of telomere maintenance via telomerase',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0045841':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '29',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.034',
        't type': 'BP',
        't group': '11',
        't name': 'negative regulation of mitotic metaphase/anaphase transition',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0071174':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '29',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.034',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic spindle checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0007094':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '27',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.037',
        't type': 'BP',
        't group': '11',
        't name': 'mitotic spindle assembly checkpoint',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0031929':
      { signf: '!',
        pvalue: '8.32e-03',
        T: '100',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'BP',
        't group': '10',
        't name': 'TOR signaling',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0038202':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '33',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.030',
        't type': 'BP',
        't group': '10',
        't name': 'TORC1 signaling',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0032006':
      { signf: '!',
        pvalue: '7.64e-03',
        T: '86',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.012',
        't type': 'BP',
        't group': '10',
        't name': 'regulation of TOR signaling',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1903432':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '27',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.037',
        't type': 'BP',
        't group': '10',
        't name': 'regulation of TORC1 signaling',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0032007':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '40',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.025',
        't type': 'BP',
        't group': '10',
        't name': 'negative regulation of TOR signaling',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1904262':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '14',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.071',
        't type': 'BP',
        't group': '10',
        't name': 'negative regulation of TORC1 signaling',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0051409':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '5',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.200',
        't type': 'BP',
        't group': '21',
        't name': 'response to nitrosative stress',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0036289':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '5',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.200',
        't type': 'BP',
        't group': '2',
        't name': 'peptidyl-serine autophosphorylation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0007568':
      { signf: '!',
        pvalue: '7.93e-03',
        T: '91',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.011',
        't type': 'BP',
        't group': '3',
        't name': 'aging',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0007569':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '65',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'BP',
        't group': '3',
        't name': 'cell aging',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0090399':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '11',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.091',
        't type': 'BP',
        't group': '3',
        't name': 'replicative senescence',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0051321':
      { signf: '!',
        pvalue: '9.49e-03',
        T: '138',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '17',
        't name': 'meiotic cell cycle',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:1903046':
      { signf: '!',
        pvalue: '8.77e-03',
        T: '116',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.009',
        't type': 'BP',
        't group': '17',
        't name': 'meiotic cell cycle process',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0140013':
      { signf: '!',
        pvalue: '8.53e-03',
        T: '110',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.009',
        't type': 'BP',
        't group': '17',
        't name': 'meiotic nuclear division',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0007127':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '73',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.014',
        't type': 'BP',
        't group': '17',
        't name': 'meiosis I',
        't depth': '4',
        'Q&T list': 'ATM' },
     'GO:0006310':
      { signf: '!',
        pvalue: '1.07e-02',
        T: '179',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '17',
        't name': 'DNA recombination',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0035825':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '41',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.024',
        't type': 'BP',
        't group': '17',
        't name': 'homologous recombination',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0007131':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '41',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.024',
        't type': 'BP',
        't group': '17',
        't name': 'reciprocal meiotic recombination',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0000732':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '26',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.038',
        't type': 'BP',
        't group': '17',
        't name': 'strand displacement',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0070661':
      { signf: '!',
        pvalue: '1.04e-02',
        T: '172',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '15',
        't name': 'leukocyte proliferation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0032943':
      { signf: '!',
        pvalue: '1.01e-02',
        T: '162',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '15',
        't name': 'mononuclear cell proliferation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0070663':
      { signf: '!',
        pvalue: '9.36e-03',
        T: '132',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.008',
        't type': 'BP',
        't group': '15',
        't name': 'regulation of leukocyte proliferation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0032944':
      { signf: '!',
        pvalue: '9.30e-03',
        T: '126',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.008',
        't type': 'BP',
        't group': '15',
        't name': 'regulation of mononuclear cell proliferation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0070664':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '37',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.027',
        't type': 'BP',
        't group': '15',
        't name': 'negative regulation of leukocyte proliferation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0032945':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '34',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.029',
        't type': 'BP',
        't group': '15',
        't name': 'negative regulation of mononuclear cell proliferation',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0050866':
      { signf: '!',
        pvalue: '8.14e-03',
        T: '97',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'BP',
        't group': '15',
        't name': 'negative regulation of cell activation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0042113':
      { signf: '!',
        pvalue: '1.13e-02',
        T: '195',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.005',
        't type': 'BP',
        't group': '15',
        't name': 'B cell activation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0046651':
      { signf: '!',
        pvalue: '1.00e-02',
        T: '160',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '15',
        't name': 'lymphocyte proliferation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0050670':
      { signf: '!',
        pvalue: '9.30e-03',
        T: '125',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.008',
        't type': 'BP',
        't group': '15',
        't name': 'regulation of lymphocyte proliferation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0042100':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '63',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.016',
        't type': 'BP',
        't group': '15',
        't name': 'B cell proliferation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0050864':
      { signf: '!',
        pvalue: '8.77e-03',
        T: '115',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.009',
        't type': 'BP',
        't group': '15',
        't name': 'regulation of B cell activation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0030888':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '37',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.027',
        't type': 'BP',
        't group': '15',
        't name': 'regulation of B cell proliferation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0002695':
      { signf: '!',
        pvalue: '7.61e-03',
        T: '83',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.012',
        't type': 'BP',
        't group': '15',
        't name': 'negative regulation of leukocyte activation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0051250':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '71',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.014',
        't type': 'BP',
        't group': '15',
        't name': 'negative regulation of lymphocyte activation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0050869':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '19',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.053',
        't type': 'BP',
        't group': '15',
        't name': 'negative regulation of B cell activation',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0050672':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '34',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.029',
        't type': 'BP',
        't group': '15',
        't name': 'negative regulation of lymphocyte proliferation',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0030889':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '11',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.091',
        't type': 'BP',
        't group': '15',
        't name': 'negative regulation of B cell proliferation',
        't depth': '4',
        'Q&T list': 'ATM' },
     'GO:0030098':
      { signf: '!',
        pvalue: '1.13e-02',
        T: '193',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.005',
        't type': 'BP',
        't group': '15',
        't name': 'lymphocyte differentiation',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0030183':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '76',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.013',
        't type': 'BP',
        't group': '15',
        't name': 'B cell differentiation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:0002327':
      { signf: '!',
        pvalue: '7.29e-03',
        T: '6',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.167',
        't type': 'BP',
        't group': '15',
        't name': 'immature B cell differentiation',
        't depth': '3',
        'Q&T list': 'ATM' },
     'GO:0009266':
      { signf: '!',
        pvalue: '9.49e-03',
        T: '139',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'BP',
        't group': '20',
        't name': 'response to temperature stimulus',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0009408':
      { signf: '!',
        pvalue: '8.69e-03',
        T: '113',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.009',
        't type': 'BP',
        't group': '20',
        't name': 'response to heat',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0034605':
      { signf: '!',
        pvalue: '8.13e-03',
        T: '96',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'BP',
        't group': '20',
        't name': 'cellular response to heat',
        't depth': '2',
        'Q&T list': 'ATM' },
     'GO:1900034':
      { signf: '!',
        pvalue: '7.34e-03',
        T: '77',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.013',
        't type': 'BP',
        't group': '20',
        't name': 'regulation of cellular response to heat',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0006403':
      { signf: '!',
        pvalue: '1.11e-02',
        T: '188',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.005',
        't type': 'BP',
        't group': '26',
        't name': 'RNA localization',
        't depth': '1',
        'Q&T list': 'ATM' },
     'GO:0051236':
      { signf: '!',
        pvalue: '9.98e-03',
        T: '156',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'BP',
        't group': '26',
        't name': 'establishment of RNA localization',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:5693532':
      { signf: '!',
        pvalue: '1.62e-02',
        T: '166',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'rea',
        't group': '24',
        't name': 'DNA Double-Strand Break Repair',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:5693538':
      { signf: '!',
        pvalue: '1.47e-02',
        T: '138',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'rea',
        't group': '24',
        't name': 'Homology Directed Repair',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:5693567':
      { signf: '!',
        pvalue: '1.44e-02',
        T: '132',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.008',
        't type': 'rea',
        't group': '24',
        't name': 'HDR through Homologous Recombination (HR) or Single Strand Annealing (SSA)',
        't depth': '3',
        'Q&T list': 'ATM' },
     'REAC:5685938':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '37',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.027',
        't type': 'rea',
        't group': '24',
        't name': 'HDR through Single Strand Annealing (SSA)',
        't depth': '4',
        'Q&T list': 'ATM' },
     'REAC:5693607':
      { signf: '!',
        pvalue: '1.17e-02',
        T: '98',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'rea',
        't group': '24',
        't name': 'Processing of DNA double-strand break ends',
        't depth': '4',
        'Q&T list': 'ATM' },
     'REAC:5685942':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '67',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'rea',
        't group': '24',
        't name': 'HDR through Homologous Recombination (HRR)',
        't depth': '4',
        'Q&T list': 'ATM' },
     'REAC:5693579':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '42',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.024',
        't type': 'rea',
        't group': '24',
        't name': 'Homologous DNA Pairing and Strand Exchange',
        't depth': '5',
        'Q&T list': 'ATM' },
     'REAC:5693616':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '39',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.026',
        't type': 'rea',
        't group': '24',
        't name': 'Presynaptic phase of homologous DNA pairing and strand exchange',
        't depth': '6',
        'Q&T list': 'ATM' },
     'REAC:5693537':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '34',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.029',
        't type': 'rea',
        't group': '24',
        't name': 'Resolution of D-Loop Structures',
        't depth': '5',
        'Q&T list': 'ATM' },
     'REAC:5693568':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '33',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.030',
        't type': 'rea',
        't group': '24',
        't name': 'Resolution of D-loop Structures through Holliday Junction Intermediates',
        't depth': '6',
        'Q&T list': 'ATM' },
     'REAC:5693554':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '26',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.038',
        't type': 'rea',
        't group': '24',
        't name': 'Resolution of D-loop Structures through Synthesis-Dependent Strand Annealing (SDSA)',
        't depth': '6',
        'Q&T list': 'ATM' },
     'REAC:5693606':
      { signf: '!',
        pvalue: '1.13e-02',
        T: '77',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.013',
        't type': 'rea',
        't group': '24',
        't name': 'DNA Double Strand Break Response',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:5693548':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '6',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.167',
        't type': 'rea',
        't group': '24',
        't name': 'Sensing of DNA Double Strand Breaks',
        't depth': '3',
        'Q&T list': 'ATM' },
     'REAC:5693565':
      { signf: '!',
        pvalue: '1.13e-02',
        T: '76',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.013',
        't type': 'rea',
        't group': '24',
        't name': 'Recruitment and ATM-mediated phosphorylation of repair and signaling proteins at DNA double strand breaks',
        't depth': '3',
        'Q&T list': 'ATM' },
     'REAC:5693571':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '69',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.014',
        't type': 'rea',
        't group': '24',
        't name': 'Nonhomologous End-Joining (NHEJ)',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:6796648':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '65',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'rea',
        't group': '9',
        't name': 'TP53 Regulates Transcription of DNA Repair Genes',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:5633008':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '44',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.023',
        't type': 'rea',
        't group': '16',
        't name': 'TP53 Regulates Transcription of Cell Death Genes',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:6803204':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '20',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.050',
        't type': 'rea',
        't group': '16',
        't name': 'TP53 Regulates Transcription of Genes Involved in Cytochrome C Release',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:6803207':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '12',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.083',
        't type': 'rea',
        't group': '16',
        't name': 'TP53 Regulates Transcription of Caspase Activators and Caspases',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:1474165':
      { signf: '!',
        pvalue: '1.51e-02',
        T: '146',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.007',
        't type': 'rea',
        't group': '14',
        't name': 'Reproduction',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:3371556':
      { signf: '!',
        pvalue: '1.18e-02',
        T: '102',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.010',
        't type': 'rea',
        't group': '19',
        't name': 'Cellular response to heat stress',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:3371453':
      { signf: '!',
        pvalue: '1.15e-02',
        T: '84',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.012',
        't type': 'rea',
        't group': '19',
        't name': 'Regulation of HSF1-mediated heat shock response',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:2559583':
      { signf: '!',
        pvalue: '1.83e-02',
        T: '196',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.005',
        't type': 'rea',
        't group': '18',
        't name': 'Cellular Senescence',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:2559586':
      { signf: '!',
        pvalue: '1.13e-02',
        T: '80',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.013',
        't type': 'rea',
        't group': '18',
        't name': 'DNA Damage/Telomere Stress Induced Senescence',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:1500620':
      { signf: '!',
        pvalue: '1.35e-02',
        T: '120',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.008',
        't type': 'rea',
        't group': '7',
        't name': 'Meiosis',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:912446':
      { signf: '!',
        pvalue: '1.16e-02',
        T: '88',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.011',
        't type': 'rea',
        't group': '7',
        't name': 'Meiotic recombination',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:69615':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '69',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.014',
        't type': 'rea',
        't group': '25',
        't name': 'G1/S DNA Damage Checkpoints',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:69580':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '67',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'rea',
        't group': '25',
        't name': 'p53-Dependent G1/S DNA damage checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:69563':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '67',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.015',
        't type': 'rea',
        't group': '25',
        't name': 'p53-Dependent G1 DNA Damage Response',
        't depth': '3',
        'Q&T list': 'ATM' },
     'REAC:69541':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '58',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.017',
        't type': 'rea',
        't group': '25',
        't name': 'Stabilization of p53',
        't depth': '4',
        'Q&T list': 'ATM' },
     'REAC:349425':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '53',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.019',
        't type': 'rea',
        't group': '25',
        't name': 'Autodegradation of the E3 ubiquitin ligase COP1',
        't depth': '5',
        'Q&T list': 'ATM' },
     'REAC:69613':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '54',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.019',
        't type': 'rea',
        't group': '25',
        't name': 'p53-Independent G1/S DNA damage checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:69610':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '54',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.019',
        't type': 'rea',
        't group': '25',
        't name': 'p53-Independent DNA Damage Response',
        't depth': '3',
        'Q&T list': 'ATM' },
     'REAC:69601':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '54',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.019',
        't type': 'rea',
        't group': '25',
        't name': 'Ubiquitin Mediated Degradation of Phosphorylated Cdc25A',
        't depth': '4',
        'Q&T list': 'ATM' },
     'REAC:5633007':
      { signf: '!',
        pvalue: '1.61e-02',
        T: '160',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'rea',
        't group': '23',
        't name': 'Regulation of TP53 Activity',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:6804760':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '19',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.053',
        't type': 'rea',
        't group': '23',
        't name': 'Regulation of TP53 Activity through Methylation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:6804756':
      { signf: '!',
        pvalue: '1.17e-02',
        T: '92',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.011',
        't type': 'rea',
        't group': '23',
        't name': 'Regulation of TP53 Activity through Phosphorylation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:6806003':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '37',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.027',
        't type': 'rea',
        't group': '23',
        't name': 'Regulation of TP53 Expression and Degradation',
        't depth': '2',
        'Q&T list': 'ATM' },
     'REAC:6804757':
      { signf: '!',
        pvalue: '1.10e-02',
        T: '36',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.028',
        't type': 'rea',
        't group': '23',
        't name': 'Regulation of TP53 Degradation',
        't depth': '3',
        'Q&T list': 'ATM' },
     'REAC:69481':
      { signf: '!',
        pvalue: '1.62e-02',
        T: '169',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.006',
        't type': 'rea',
        't group': '22',
        't name': 'G2/M Checkpoints',
        't depth': '1',
        'Q&T list': 'ATM' },
     'REAC:69473':
      { signf: '!',
        pvalue: '1.17e-02',
        T: '95',
        'Q&T': '1',
        'Q&T/Q': '1.000',
        'Q&T/T': '0.011',
        't type': 'rea',
        't group': '22',
        't name': 'G2/M DNA damage checkpoint',
        't depth': '2',
        'Q&T list': 'ATM' } };

      expect(res).to.deep.equal(result);
    });
  });
});